# cluster, node 이름 지정
cluster.name: "es-cluster-1"
node.name: "node-1"

# data, logs 경로 지정-1
path.data: "/home/choihm9903/data"
path.logs: "/home/choihm9903/logs"

# data, logs 경로 지정-2
path:
  data: "/home/choihm9903/data"
  logs: "/home/choihm9903/logs"